### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by anazcodes** [misikdmytro/go-scheduler#1]
The Docker compose file lacks complete isolation. 
![Screenshot from 2023-09-17 15-19-11](https://github.com/misikdmytro/go-scheduler/assets/121440151/c25f11da-271d-4f79-8f36-2dd3fe18b3ca)

**Comment by misikdmytro** [comment]
@anazibinurasheed thanks for your review! I'm not sure I understand your issue correctly, can you explain it a little bit? appreciate your help!

**Comment by anazcodes** [comment]
We know that with using docker compose and docker anyone can run the app using a single docker compose up command, I found your repo from the docs, I don't know if the issue is only for me or not. But I just reported the issue because maybe other users also read your docs.

**Comment by anazcodes** [comment]
The issue: While deploying the app on the local machine the Docker compose shows the error while connecting the postgres.

**Comment by misikdmytro** [comment]
Thanks @anazibinurasheed for your answer! That's designed behavior to be able to start the whole application together with infrastructure with single 'docker compose up' command. It makes easy for new developers to start and maintain application locally. That's why docker compose used here. Connection errors in logs might be an issue, I'll check it.
